
<template>
  <div class="container mx-auto p-4 md:p-8 max-w-7xl">
    <!-- Header -->
    <header class="text-center mb-8">
        <div class="flex justify-center items-center gap-4">
            <h1 class="text-3xl md:text-4xl font-bold text-blue-800">銘傳大學電機工程學系</h1>
            <button @click="showQrModal" class="text-gray-500 hover:text-blue-600 p-2 rounded-full transition-colors duration-200" title="分享此頁面 (QR Code)">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h4v4H4zM16 4h4v4h-4zM4 16h4v4H4zM16 16h4v4h-4zM10 4h4M10 20h4M4 10h4M16 10h4M10 10h4v4h-4z"/></svg>
            </button>
        </div>
        <p class="text-lg md:text-xl text-gray-600 mt-2">114學年度入學生適用課程架構</p>
    </header>

    <!-- Graduation Credits -->
    <div class="bg-white p-6 rounded-xl shadow-md mb-8 border border-gray-200">
        <h2 class="text-2xl font-bold text-gray-700 mb-4">畢業學分規定</h2>
        <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4 text-center">
            <div class="bg-blue-50 p-4 rounded-lg">
                <p class="text-sm text-blue-700 font-semibold">必修學分</p>
                <p class="text-2xl font-bold text-blue-900">74</p>
            </div>
            <div class="bg-green-50 p-4 rounded-lg">
                <p class="text-sm text-green-700 font-semibold">專業選修</p>
                <p class="text-2xl font-bold text-green-900">33</p>
            </div>
            <div class="bg-yellow-50 p-4 rounded-lg">
                <p class="text-sm text-yellow-700 font-semibold">外系選修</p>
                <p class="text-2xl font-bold text-yellow-900">21</p>
            </div>
             <div class="bg-indigo-50 p-4 rounded-lg">
                <p class="text-sm text-indigo-700 font-semibold">最低選修</p>
                <p class="text-2xl font-bold text-indigo-900">54</p>
            </div>
            <div class="bg-red-50 p-4 rounded-lg col-span-2 md:col-span-1 lg:col-span-1">
                <p class="text-sm text-red-700 font-semibold">畢業總學分</p>
                <p class="text-2xl font-bold text-red-900">128</p>
            </div>
        </div>
    </div>

    <!-- Course Tabs -->
    <div class="mb-6">
        <div class="border-b border-gray-200">
            <nav class="-mb-px flex space-x-4 overflow-x-auto" aria-label="Tabs">
                <button @click="showTab('required', $event)" class="tab tab-active whitespace-nowrap py-3 px-4 border-b-2 font-semibold text-sm">校定必修</button>
                <button @click="showTab('major-required', $event)" class="tab tab-inactive whitespace-nowrap py-3 px-4 border-b-2 font-semibold text-sm">專業必修</button>
                <button @click="showTab('major-elective', $event)" class="tab tab-inactive whitespace-nowrap py-3 px-4 border-b-2 font-semibold text-sm">專業選修</button>
                <button @click="showTab('other-elective', $event)" class="tab tab-inactive whitespace-nowrap py-3 px-4 border-b-2 font-semibold text-sm">其他選修</button>
            </nav>
        </div>
    </div>

    <!-- Course Content -->
    <main id="course-content">
        <!-- Required -->
        <div id="required" class="tab-content">
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <!-- Content will be generated by JS -->
            </div>
        </div>

        <!-- Major Required -->
        <div id="major-required" class="tab-content hidden">
             <div class="overflow-x-auto bg-white rounded-lg shadow">
                <table class="min-w-full text-sm text-left text-gray-600">
                    <thead class="bg-gray-100 text-xs text-gray-700 uppercase">
                        <tr>
                            <th scope="col" class="px-6 py-3">課程名稱</th>
                            <th scope="col" class="px-6 py-3">學分</th>
                            <th scope="col" class="px-6 py-3">開課學期</th>
                        </tr>
                    </thead>
                    <tbody id="major-required-table">
                        <!-- Content will be generated by JS -->
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Major Elective -->
        <div id="major-elective" class="tab-content hidden">
            <!-- Sub-tabs -->
            <div class="mb-6">
                <div class="border-b border-gray-200">
                    <nav class="-mb-px flex space-x-4 overflow-x-auto" aria-label="SubTabs">
                        <button @click="showSubTab('elective-iot', $event)" class="sub-tab tab-active whitespace-nowrap py-2 px-3 border-b-2 font-medium text-xs">智慧聯網</button>
                        <button @click="showSubTab('elective-network', $event)" class="sub-tab tab-inactive whitespace-nowrap py-2 px-3 border-b-2 font-medium text-xs">智慧網路與通訊</button>
                        <button @click="showSubTab('elective-semi', $event)" class="sub-tab tab-inactive whitespace-nowrap py-2 px-3 border-b-2 font-medium text-xs">半導體光電</button>
                        <button @click="showSubTab('elective-chip', $event)" class="sub-tab tab-inactive whitespace-nowrap py-2 px-3 border-b-2 font-medium text-xs">晶片設計與應用</button>
                    </nav>
                </div>
            </div>
            <div id="major-elective-content">
                <!-- Content will be generated by JS -->
            </div>
        </div>

        <!-- Other Elective -->
        <div id="other-elective" class="tab-content hidden">
             <div class="overflow-x-auto bg-white rounded-lg shadow">
                <table class="min-w-full text-sm text-left text-gray-600">
                    <thead class="bg-gray-100 text-xs text-gray-700 uppercase">
                        <tr>
                            <th scope="col" class="px-6 py-3">課程名稱</th>
                            <th scope="col" class="px-6 py-3">學分</th>
                            <th scope="col" class="px-6 py-3">開課學期</th>
                            <th scope="col" class="px-6 py-3">備註</th>
                        </tr>
                    </thead>
                    <tbody id="other-elective-table">
                        <!-- Content will be generated by JS -->
                    </tbody>
                </table>
            </div>
        </div>
    </main>
</div>
</template>

<script setup>
import { onMounted, ref } from 'vue';

// This would typically be handled by a build process or environment variables
const hasApiKey = ref(false); // Set to true if you have an API key

const courses = {
    required: [
        { name: '人工智慧概論', credits: 2, semester: '一上', note: '' },
        { name: '中國文學鑑賞與創作(一)', credits: 2, semester: '一上', note: '' },
        { name: '中國文學鑑賞與創作(二)', credits: 2, semester: '一下', note: '' },
        { name: '應用英文(一)', credits: 2, semester: '一上', note: '' },
        { name: '應用英文(二)', credits: 2, semester: '一下', note: '' },
        { name: '應用英文(三)', credits: 2, semester: '二上', note: '' },
        { name: '應用英文(四)', credits: 2, semester: '二下', note: '' },
        { name: '商務溝通英文(一)', credits: 2, semester: '三上', note: '備註1' },
        { name: '商務溝通英文(二)', credits: 2, semester: '三下', note: '' },
        { name: '職場應用英文(一)', credits: 2, semester: '四上', note: '' },
        { name: '職場應用英文(二)', credits: 2, semester: '四下', note: '' },
        { name: '體育(壹~肆)', credits: 0, semester: '一上~二下', note: '備註2' },
        { name: '通識教育', credits: 8, semester: '依學校規定', note: '' },
    ],
    majorRequired: [
        { name: '數位邏輯設計', credits: 3, semester: '一上' },
        { name: '數位邏輯設計實驗', credits: 1, semester: '一上' },
        { name: '程式設計(一)', credits: 3, semester: '一上' },
        { name: '微積分(一)', credits: 3, semester: '一上' },
        { name: '程式設計(二)', credits: 3, semester: '一下' },
        { name: '微積分(二)', credits: 3, semester: '一下' },
        { name: '計算機概論', credits: 3, semester: '一下' },
        { name: '電路學(一)', credits: 3, semester: '一下' },
        { name: '電路學(二)', credits: 3, semester: '二上' },
        { name: '工程數學(一)', credits: 3, semester: '二上' },
        { name: '電子電路實驗(一)', credits: 1, semester: '二上' },
        { name: '電子學(一)', credits: 3, semester: '二上' },
        { name: '電子學(二)', credits: 3, semester: '二下' },
        { name: '電磁學(一)', credits: 3, semester: '二下' },
        { name: '微處理機原理與實習', credits: 3, semester: '二下' },
        { name: '電子電路實驗(二)', credits: 1, semester: '二下' },
        { name: '專題研究(一)', credits: 3, semester: '三下' },
        { name: '專題研究(二)', credits: 3, semester: '四上' },
    ],
    majorElective: {
        iot: [
            { name: '物聯網系統', credits: 3, semester: '二上' },
            { name: '計算機組織與結構', credits: 3, semester: '二上' },
            { name: '機器學習導論', credits: 3, semester: '二下' },
            { name: '智慧演算法', credits: 3, semester: '二下' },
            { name: '線性控制系統', credits: 3, semester: '三上' },
            { name: '電子學(三)', credits: 3, semester: '三上' },
            { name: '嵌入式系統', credits: 3, semester: '三下' },
            { name: '機器人控制', credits: 3, semester: '三下' },
            { name: '數位影像處理', credits: 3, semester: '四上' },
            { name: '微電腦通信', credits: 3, semester: '四上' },
            { name: '資料壓縮', credits: 3, semester: '四上' },
            { name: '單晶片控制', credits: 3, semester: '四上' },
            { name: '電腦視覺', credits: 3, semester: '四下' },
            { name: '深度學習概論', credits: 3, semester: '四下' },
        ],
        network: [
            { name: '資料庫程式設計', credits: 3, semester: '一上' },
            { name: 'JAVA程式設計', credits: 3, semester: '一下' },
            { name: '機率與統計', credits: 3, semester: '一下' },
            { name: '作業系統', credits: 3, semester: '二上' },
            { name: 'JAVA 應用程式設計', credits: 3, semester: '二上' },
            { name: '電腦網路概論', credits: 3, semester: '二上' },
            { name: '訊號與系統', credits: 3, semester: '二下' },
            { name: '離散數學', credits: 3, semester: '二下' },
            { name: '通訊導論', credits: 3, semester: '二下' },
            { name: '網路規劃', credits: 3, semester: '三上' },
            { name: '網路管理', credits: 3, semester: '三上' },
            { name: '通訊原理', credits: 3, semester: '三上' },
            { name: '微波工程', credits: 3, semester: '三上' },
            { name: '數位訊號處理', credits: 3, semester: '三上' },
            { name: '網路原理與技術', credits: 3, semester: '三下' },
            { name: '數位通訊', credits: 3, semester: '四上' },
            { name: '網路程式設計', credits: 3, semester: '四上' },
            { name: '廣域網路', credits: 3, semester: '四下' },
            { name: '網際網路應用', credits: 3, semester: '四下' },
            { name: 'Web 程式設計', credits: 3, semester: '四下' },
            { name: 'APP程式設計', credits: 3, semester: '四下' },
            { name: '資訊安全導論', credits: 3, semester: '四下' },
            { name: '區域網路', credits: 3, semester: '四下' },
            { name: '雲端計算', credits: 3, semester: '四下' },
        ],
        semi: [
            { name: '物理學', credits: 3, semester: '一上' },
            { name: '近代物理', credits: 3, semester: '一下' },
            { name: '工程數學(二)', credits: 3, semester: '二下' },
            { name: '半導體元件導論', credits: 3, semester: '二下' },
            { name: '電子電路實驗(三)', credits: 1, semester: '三上' },
            { name: '光纖通訊', credits: 3, semester: '三上' },
            { name: '光電元件導論', credits: 3, semester: '三上' },
            { name: '電磁學(二)', credits: 3, semester: '三上' },
            { name: '電子材料概論', credits: 3, semester: '三下' },
            { name: '光電設計與應用', credits: 3, semester: '三下' },
            { name: '半導體量測', credits: 3, semester: '三下' },
            { name: '平面顯示器概論', credits: 3, semester: '三下' },
            { name: '記憶體元件導論', credits: 3, semester: '三下' },
            { name: '電磁波', credits: 3, semester: '三下' },
            { name: '固態電子學', credits: 3, semester: '三下' },
            { name: '奈米電子元件', credits: 3, semester: '四上' },
            { name: '半導體製程概論', credits: 3, semester: '四上' },
            { name: '太陽電池導論', credits: 3, semester: '四上' },
            { name: '半導體可靠度工程導論', credits: 3, semester: '四上' },
            { name: '光電系統設計與應用', credits: 3, semester: '四下' },
            { name: '矽光子元件', credits: 3, semester: '四下' },
        ],
        chip: [
            { name: '物理學', credits: 3, semester: '一上' },
            { name: '電路學(二)', credits: 3, semester: '二上' },
            { name: '電路模擬設計實習(spice)', credits: 3, semester: '二上' },
            { name: 'OrCAD 電路設計', credits: 3, semester: '三上' },
            { name: 'Verilog 程式設計', credits: 3, semester: '三上' },
            { name: '超大型積體電路導論', credits: 3, semester: '三上' },
            { name: '電子電路實驗(三)', credits: 3, semester: '三下' },
            { name: 'OrCAD 電路佈線', credits: 3, semester: '三下' },
            { name: 'FPGA/CPLD設計', credits: 3, semester: '三下' },
            { name: '電子電路設計', credits: 3, semester: '三下' },
            { name: '微處理機通訊', credits: 3, semester: '三下' },
            { name: '嵌入式系統', credits: 3, semester: '三下' },
            { name: '物聯網實務應用', credits: 3, semester: '四上' },
            { name: '數位積體電路設計', credits: 3, semester: '四上' },
            { name: '超大積體電路導論', credits: 3, semester: '四上' },
            { name: '積體電路佈局設計', credits: 3, semester: '四下' },
            { name: '類比積體電路設計', credits: 3, semester: '四下' },
            { name: '電腦輔助半導體設計', credits: 3, semester: '四下' },
        ]
    },
    otherElective: [
        { name: '線性代數', credits: 3, semester: '一上', note: '' },
        { name: '資料結構', credits: 3, semester: '一下', note: '' },
        { name: 'Python 程式設計', credits: 3, semester: '一下', note: '' },
        { name: '作業系統實務', credits: 3, semester: '一下', note: '' },
        { name: '工程應用軟體', credits: 3, semester: '二上', note: '' },
        { name: '控制系統', credits: 3, semester: '二上', note: '' },
        { name: '訊號與系統', credits: 3, semester: '二下', note: '' },
        { name: '深度學習概論', credits: 3, semester: '二下', note: '' },
        { name: '工程應用軟體', credits: 3, semester: '三上', note: '' },
        { name: '電子學(三)', credits: 3, semester: '三上', note: '' },
        { name: '線性電路設計', credits: 3, semester: '三上', note: '' },
        { name: '通訊系統', credits: 3, semester: '三下', note: '' },
        { name: '電機工程講座', credits: 1, semester: '四上', note: '' },
        { name: '企業實習', credits: 3, semester: '四上', note: '' },
        { name: '企業進階實習', credits: 3, semester: '四下', note: '' },
        { name: '職場實務專題', credits: 3, semester: '四下', note: '' },
        { name: '職場英文', credits: 3, semester: '一下', note: '' },
        { name: '體育(三上)', credits: 2, semester: '三上', note: '大三體育只承認2學分' },
        { name: '體育(三下)', credits: 2, semester: '三下', note: '' },
        { name: '體育(四上)', credits: 2, semester: '四上', note: '大四體育只承認2學分' },
        { name: '體育(四下)', credits: 2, semester: '四下', note: '' },
    ]
};

let qrCodeGenerated = false;

function showModal() {
    document.getElementById('gemini-modal').classList.remove('hidden');
}

function closeModal() {
    document.getElementById('gemini-modal').classList.add('hidden');
}

async function generateDescription(courseName) {
    if (!hasApiKey.value) {
        document.getElementById('modal-title').innerText = `功能無法使用`;
        document.getElementById('modal-body').innerHTML = `<p class="text-gray-600">此功能需要 API 金鑰才能運作。在目前的部署環境中未提供金鑰。</p>`;
        showModal();
        return;
    }
    // ... (rest of the function)
}

function showQrModal() {
    const qrModal = document.getElementById('qr-modal');
    qrModal.classList.remove('hidden');
    if (!qrCodeGenerated) {
        const qrContainer = document.getElementById('qrcode-container');
        const canvas = document.createElement('canvas');
        qrContainer.appendChild(canvas);
        window.QRCode.toCanvas(canvas, 'https://jimmy0108.github.io/myself/EE_class', { width: 220, margin: 2 }, function (error) {
            if (error) console.error(error);
            qrCodeGenerated = true;
        });
    }
}

function closeQrModal() {
    document.getElementById('qr-modal').classList.add('hidden');
}

function createGeminiButton(courseName) {
    if (!hasApiKey.value) {
        return '';
    }
    return `
        <button onclick="window.generateDescription('${courseName}')" 
                class="ml-2 text-sm text-blue-500 hover:text-blue-700 transition-colors duration-200" 
                title="✨ AI 產生課程說明">
            ✨
        </button>
    `;
}

function renderRequired() {
    const container = document.querySelector('#required .grid');
    let html = '';
    courses.required.forEach(course => {
        html += `
            <div class="bg-white p-5 rounded-lg shadow border border-gray-100 flex flex-col justify-between">
                <div>
                    <h3 class="font-bold text-gray-800 flex items-center">
                        ${course.name}
                        ${createGeminiButton(course.name)}
                    </h3>
                    <p class="text-sm text-gray-500 mt-1">開課學期: ${course.semester}</p>
                </div>
                <div class="flex justify-between items-center mt-3">
                    <span class="text-xs font-semibold inline-block py-1 px-2 uppercase rounded-full text-blue-600 bg-blue-200">
                        ${course.credits} 學分
                    </span>
                    ${course.note ? `<span class="text-xs text-red-600">${course.note}</span>` : ''}
                </div>
            </div>
        `;
    });
    container.innerHTML = html;
}

function renderMajorRequired() {
    const tbody = document.getElementById('major-required-table');
    let html = '';
    courses.majorRequired.forEach((course, index) => {
        html += `
            <tr class="${index % 2 === 0 ? 'bg-white' : 'bg-gray-50'} border-b">
                <td class="px-6 py-4 font-medium text-gray-900">
                    <div class="flex items-center">
                        ${course.name}
                        ${createGeminiButton(course.name)}
                    </div>
                </td>
                <td class="px-6 py-4">${course.credits}</td>
                <td class="px-6 py-4">${course.semester}</td>
            </tr>
        `;
    });
    tbody.innerHTML = html;
}

function renderMajorElective(group) {
    const container = document.getElementById('major-elective-content');
    const groupCourses = courses.majorElective[group];
    let tableHtml = `
        <div class="overflow-x-auto bg-white rounded-lg shadow">
            <table class="min-w-full text-sm text-left text-gray-600">
                <thead class="bg-gray-100 text-xs text-gray-700 uppercase">
                    <tr>
                        <th scope="col" class="px-6 py-3">課程名稱</th>
                        <th scope="col" class="px-6 py-3">學分</th>
                        <th scope="col" class="px-6 py-3">開課學期</th>
                    </tr>
                </thead>
                <tbody>
    `;
    groupCourses.forEach((course, index) => {
        tableHtml += `
            <tr class="${index % 2 === 0 ? 'bg-white' : 'bg-gray-50'} border-b">
                <td class="px-6 py-4 font-medium text-gray-900">
                    <div class="flex items-center">
                        ${course.name}
                        ${createGeminiButton(course.name)}
                    </div>
                </td>
                <td class="px-6 py-4">${course.credits}</td>
                <td class="px-6 py-4">${course.semester}</td>
            </tr>
        `;
    });
    tableHtml += `</tbody></table></div>`;
    container.innerHTML = tableHtml;
}

function renderOtherElective() {
    const tbody = document.getElementById('other-elective-table');
    let html = '';
    courses.otherElective.forEach((course, index) => {
        html += `
            <tr class="${index % 2 === 0 ? 'bg-white' : 'bg-gray-50'} border-b">
                <td class="px-6 py-4 font-medium text-gray-900">
                    <div class="flex items-center">
                        ${course.name}
                        ${createGeminiButton(course.name)}
                    </div>
                </td>
                <td class="px-6 py-4">${course.credits}</td>
                <td class="px-6 py-4">${course.semester}</td>
                <td class="px-6 py-4 text-red-600 text-xs">${course.note}</td>
            </tr>
        `;
    });
    tbody.innerHTML = html;
}

function showTab(tabId, event) {
    const contents = document.querySelectorAll('.tab-content');
    contents.forEach(content => content.classList.add('hidden'));
    document.getElementById(tabId).classList.remove('hidden');

    const tabs = document.querySelectorAll('.tab');
    tabs.forEach(tab => {
        tab.classList.remove('tab-active');
        tab.classList.add('tab-inactive');
    });
    event.target.classList.add('tab-active');
    event.target.classList.remove('tab-inactive');
}

function showSubTab(subTabId, event) {
    const group = subTabId.split('-')[1];
    renderMajorElective(group);
    
    const subTabs = document.querySelectorAll('.sub-tab');
    subTabs.forEach(tab => {
        tab.classList.remove('tab-active');
        tab.classList.add('tab-inactive');
    });
    event.target.classList.add('tab-active');
    event.target.classList.remove('tab-inactive');
}

onMounted(() => {
    renderRequired();
    renderMajorRequired();
    renderMajorElective('iot');
    renderOtherElective();
    // The Gemini API call needs to be attached to the window object 
    // to be accessible from the dynamically generated HTML
    window.generateDescription = generateDescription;
});

</script>

<style scoped>
.tab-active {
    border-color: #3b82f6; /* blue-500 */
    color: #3b82f6;
    background-color: #eff6ff; /* blue-50 */
}
.tab-inactive {
    border-color: transparent;
    color: #6b7280; /* gray-500 */
}
.modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.5);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 1000;
}
.modal-content {
    background-color: white;
    padding: 2rem;
    border-radius: 0.75rem;
    max-width: 500px;
    width: 90%;
    box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
    position: relative;
}
.loader {
    border: 4px solid #f3f3f3;
    border-top: 4px solid #3498db;
    border-radius: 50%;
    width: 40px;
    height: 40px;
    animation: spin 1s linear infinite;
    margin: 2rem auto;
}
@keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
}
</style>
